---
- name: instalacao do gitlab
  hosts: gitlab
  tasks:
    - name: Instalando pre requisitos
      yum: name={{ item }} state=present
      with_items:
      - curl
      - policycoreutils-python
      - openssh-server

    - name: habilidanto o ssh
      service: name=sshd state=running enabled=true
   
   # - name: habilitando firewalld
   #   shell: firewall-cmd --permanent --add-service=http

    - name: reiniciando o firewalld
      shell: name=firewalld state=stopped 
   
    - name: instalando postfix
      yum: name=postfix state=present

    - name: habilitando postfix
      service: name=postfix state=running enabled=True

    - name: instalando gitlab
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
  
    - name: instalando o gitlab
      yum: name=gitlab-ce state=present 
